### ISSUE TITLE
Merge parse-zoneinfo with zoneinfo-parse

### ISSUE THREAD

**Issue by pitdicker** [chronotope/parse-zoneinfo#11]
@djc @ogham @djzin

Seven years ago this crate parse-zoneinfo started as a fork of zoneinfo-parse. I don't know if there was any communication, or if a fork just seemed convenient at the time.

Parse-zoneinfo did not preserve git history. The initial commit made quite a number of changes to `src/line.rs` to make the crate independent of either `datetime` or `chrono`, and to drop the dependency on `lazy_static`.

Both crates have seen only limited development since. Fixing some compiler warnings, fixing up CI, rustfmt. Parse-zoneinfo has got some compile time optimizations. Zoneinfo-parse has some more documentation.
Not that any development was needed, the crates serve the purpose of parsing the zoneinfo files.

Parse-zoneinfo has 17,6 million downloads on crates.io thanks to chrono-tz and 6 other dependents. The original zoneinfo-parse has 7000 downloads and no dependents on crates.io. Both have no open issues.

It is unfortunate there are two almost identical crates, that both have to be maintained. I propose to merge the parse-zoneinfo and zoneinfo-parse projects.

- If all agree we probably want to have shared ownership.
- Zoneinfo-parse should be the name of the crate after merging, because it was the original, to recognize @ogham for doing most of the work, and because it has the git history.
- I propose to bring over the changes to make parse-zoneinfo independent of either `datetime` or `chrono` and publish it as a new major version. Maybe 1.0, given that it works fine?
- We can either merge the git history, or turn the initial commit by @djzin into a couple of commits that apply to the current main of zoneinfo-parse and cherry-pick the ±15 other commits since then.

**Comment by pitdicker** [comment]
:disappointed: The top line in [this repo](https://github.com/ogham/exa) says @ogham cannot be reached. That probably brings this proposal to a quick end.

Then the best thing to do here is probably to port over the more complete documentation and some of the commit since the fork.

**Comment by djc** [comment]
Given that parse-zoneinfo is the far more popular crate, I'm not sure it's useful to merge these crates now. I think we should do these things:

* Merge the git history from zoneinfo_parse into this repository somehow (probably by just doing an unrelated history merge)
  * We should make sure that the current commits are still part of the new main branch's commit ancestry
* Flesh out the README of this repo with explicit recognition of @ogham's work
